services:
  db:
    container_name: ${MONGO_DB}
    image: mongo:latest
    volumes:
      - poke-vol:/data/db
    # ports:
    #   - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    command: ["--auth"]
    healthcheck:
      test: "mongo --eval 'db.runCommand({ ping: 1 })'"
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    depends_on:
      - db
    container_name: ${MONGO_EXPRESS}
    image: mongo-express:1.0.2-20-alpine3.19
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_DB}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD} 
    ports:
      - 8080:8081
    restart: always

  poke-app:
    depends_on:
      - db
      - mongo-express
    image: klerith/pokemon-nest-app:1.0.0
    container_name: ${POKE_APP}
    ports:
      - 3000:3000
    environment:
      - MONGODB=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_DB}:27017/
      - DB_NAME=${MONGO_DB}
    restart: always

volumes:
  poke-vol:
    external: false