services:
  db:
    container_name: postgres_database
    image: postgres
    volumes:
      # - postgres-db:/var/lib/postgresql/data
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mario01.
      POSTGRES_DB: postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: superman@gmail.com 
      PGADMIN_DEFAULT_PASSWORD: Mario01.

# volumes:
#   postgres-db:
#     external: true